# Generated by Django 3.2 on 2021-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_company_compan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('sector', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('website_url', models.URLField()),
                ('logo_url', models.URLField()),
                ('description', models.TextField()),
                ('market_price', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('previous_close', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('trailing_pe_ratio', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('peg_ratio', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('pb_ratio', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('fifty_two_week_low', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('fifty_two_week_high', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('fifty_two_week_change', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('beta', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dividend_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('payout_ratio', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('ex_dividend_date', models.DateField(null=True)),
                ('last_dividend_date', models.DateField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Compan',
        ),
    ]
