# Generated by Django 3.2 on 2021-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210415_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='USD', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='market_capitalization',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
