# Generated by Django 3.2 on 2021-04-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_company_market_capitalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trailing_pe_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
