# Generated by Django 3.2 on 2021-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_company_trailing_pe_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payout_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
