# Generated by Django 3.2 on 2021-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210416_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeserie',
            name='timestamp',
            field=models.DateField(unique=True),
        ),
    ]
