# Generated by Django 3.2 on 2021-04-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210417_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='beta',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
