# Generated by Django 3.2 on 2021-04-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_company_beta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
