# Generated by Django 3.2 on 2021-04-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_company_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='peg_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
