# Generated by Django 3.2 on 2021-04-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210417_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pb_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
