# Generated by Django 3.2 on 2021-04-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
