# Generated by Django 3.2 on 2021-04-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_company_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fifty_two_week_change',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fifty_two_week_high',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fifty_two_week_low',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='market_capitalization',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previous_close',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
