# Generated by Django 3.2 on 2021-04-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
