# Generated by Django 3.2 on 2021-04-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_company_isin'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('total_dividends', models.BigIntegerField()),
                ('total_revenue', models.BigIntegerField()),
                ('net_income', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
            options={
                'unique_together': {('timestamp', 'company')},
            },
        ),
    ]
