# Generated by Django 3.2 on 2021-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='beta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='dividend_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='dividend_yield',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fifty_two_week_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fifty_two_week_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fifty_two_week_low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='market_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='payout_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pb_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='peg_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='previous_close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trailing_pe_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='timeserie',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timeserie',
            name='dividends',
            field=models.FloatField(),
        ),
    ]
