# Generated by Django 3.2 on 2021-04-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210418_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dividend_growth_streak',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='dividend_streak',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
